[admin]
read =  ["users", "cities", "reports", "activities", "directors", "customers"]
write = ["users", "cities", "reports", "activities", "directors", "customers"]

[user]
read = ["users","reportes"]


