# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
# dsn= "postgres://postgres:postgres@127.0.0.1:5432/go_restful?sslmode=disable"
dsn= "root:Infra20n19+he24@127.0.0.1/infrastructure"

# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   RESTFUL_JWT_VERIFICATION_KEY
#   RESTFUL_JWT_SIGNING_KEY
jwt_verification_key= "QfCAH04Cob7b71QCqy738vw5XGSnFZ8d"
jwt_signing_key= "QfCAH04Cob7b71QCqy738vw5XGSnFZ8d"
# Uncomment the following line and set an appropriate JWT signing method, if needed
# The default signing method is HS256.
#jwt_signing_method: "HS256"
#
debug= true
default_language = "ku"

[MYSQL]
user = "root"
password = "Infra20n19+he24"
host = "127.0.0.1"
port = "3306"
database = "infrastructure"

