settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: organized-restful
  path: .
  commands:
    build:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
